server:
  port: 9091

spring:
  application:
    name: msvc-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:kjo-care-realm-dev}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:kjo-care-realm-dev}/protocol/openid-connect/certs

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:kjo-care-realm-dev}
  master-realm: ${KEYCLOAK_MASTER_REALM:master}
  admin-client: ${KEYCLOAK_ADMIN_CLIENT:admin-cli}
  user: ${KEYCLOAK_USER:admin}
  password: ${KEYCLOAK_PASSWORD:admin}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:default-secret-key}

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: client-kjo-care

login:
  level:
    org:
      keycloak: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/