eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: msvc-mood-tracking
          uri: lb://msvc-mood-tracking
          predicates:
            - Path=/api/mood-tracking/**
          filters:
            - StripPrefix=2
        - id: msvc-emergency
          uri: lb://msvc-emergency
          predicates:
            - Path=/api/emergency/**
          filters:
            - StripPrefix=2
        - id: msvc-blog
          uri: lb://msvc-blog
          predicates:
            - Path=/api/blog/**
          filters:
            - StripPrefix=2