eureka:
  instance:
    hostname: gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: msvc-auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/mind/auth/**
          filters:
            - StripPrefix=3
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/mind/users/**
          filters:
            - StripPrefix=3
        - id: msvc-mood-tracking
          uri: lb://msvc-mood-tracking
          predicates:
            - Path=/api/mind/mood-tracking/**
          filters:
            - StripPrefix=3
        - id: msvc-emergency
          uri: lb://msvc-emergency
          predicates:
            - Path=/api/mind/emergency/**
          filters:
            - StripPrefix=3
        - id: msvc-blog
          uri: lb://msvc-blog
          predicates:
            - Path=/api/mind/blog/**
          filters:
            - StripPrefix=3
        - id: msvc-analytics
          uri: lb://msvc-analytics
          predicates:
            - Path=/api/mind/analytics/**
          filters:
            - StripPrefix=3
        - id: msvc-daily-activity
          uri: lb://msvc-daily-activity
          predicates:
            - Path=/api/mind/daily-activity/**
          filters:
            - StripPrefix=3