eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    config:
      discovery:
        enabled: true
    gateway:
      mvc:
        routes: