spring:
  application:
    name: msvc-analytics
  config:
    import: optional:configserver:http://config-server:8888

#    prometheus:
#      access: unrestricted
#  prometheus:
#    metrics:
#      export:
#        enabled: true