spring:
  application:
    name: msvc-analytics
  config:
    import: optional:configserver:http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOSTNAME:localhost}:9090/realms/${KEYCLOAK_REALM:kjo-care-realm-dev}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/${KEYCLOAK_REALM:kjo-care-realm-dev}/protocol/openid-connect/certs
          audience: ${KEYCLOAK_CLIENT_ID:kjo-care-client}

jwt:
  auth:
    converter:
      principal-attribute: preferred_username
      resource-id: ${KEYCLOAK_CLIENT_ID:kjo-care-client}

server:
  port: 9005

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    enabled: true

microservices:
  mood-tracking:
    url: lb://msvc-mood-tracking
  blog:
    url: lb://msvc-blog
  emergency:
    url: lb://msvc-emergency
  auth:
    url: lb://msvc-auth

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#    prometheus:
#      access: unrestricted
#  prometheus:
#    metrics:
#      export:
#        enabled: true