CREATE USER postgres WITH PASSWORD 'postgres' SUPERUSER;
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;

CREATE DATABASE blogs;
GRANT ALL PRIVILEGES ON DATABASE blogs TO postgres;

CREATE DATABASE emergency;
GRANT ALL PRIVILEGES ON DATABASE emergency TO postgres;