-- CREATE USER postgres WITH PASSWORD 'postgres' SUPERUSER;
-- CREATE DATABASE keycloak;
-- GRANT ALL PRIVILEGES ON DATABASE keycloak TO postgres;

CREATE DATABASE blogs;
GRANT ALL PRIVILEGES ON DATABASE blogs TO postgres;

CREATE DATABASE emergency;
GRANT ALL PRIVILEGES ON DATABASE emergency TO postgres;

CREATE DATABASE mood_tracking;
GRANT ALL PRIVILEGES ON DATABASE mood_tracking TO postgres;

CREATE DATABASE notifications;
GRANT ALL PRIVILEGES ON DATABASE notifications TO postgres;