spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://config-server:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
